source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AZFramer_Example', :exclusive => true do
  pod "AZFramer", :path => "../"
end

target 'AZFramer_Tests', :exclusive => true do
  pod "AZFramer", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
